### ISSUE TITLE
Note For Reviewer

### ISSUE THREAD

**Issue by Chandan-devs-tech** [Chandan-devs-tech/drive-easy-backend#11]
- This is the link of our Final Capstone Project's Kanban Board :

  - https://github.com/users/Chandan-devs-tech/projects/7/views/1
  
- We are a team of 4 members :

  - @Chandan-devs-tech 
  - @ctokoli 
  - @Dorcas126 
  - @mariegrace31 

<img width="960" alt="1" src="https://github.com/Chandan-devs-tech/book-an-appointment/assets/65088027/dc3b0a08-6f63-4279-b87c-40a7ffb27d87">

<img width="960" alt="2" src="https://github.com/Chandan-devs-tech/book-an-appointment/assets/65088027/ad082749-65f0-46ea-91be-6c58fa8dd8cf">

<img width="958" alt="3" src="https://github.com/Chandan-devs-tech/book-an-appointment/assets/65088027/c226c149-d814-48de-a8e9-05021500bc48">

**Comment by Meltrust** [comment]
Hi @Chandan-devs-tech,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- The cards have descriptions, assignees, and pointings that meet the kanban board requirements✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Chandan-devs-tech** [comment]
https://github.com/Chandan-devs-tech/drive-easy-backend/issues/11
